//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HMSEntities : DbContext
    {
        public HMSEntities()
            : base("name=HMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APPOINTMENT> APPOINTMENTs { get; set; }
        public virtual DbSet<DOCTOR> DOCTORs { get; set; }
        public virtual DbSet<IBILL> IBILLs { get; set; }
        public virtual DbSet<OBILL> OBILLs { get; set; }
        public virtual DbSet<OPATIENT> OPATIENTs { get; set; }
        public virtual DbSet<PATIENT> PATIENTs { get; set; }
        public virtual DbSet<ROOM> ROOMs { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<string> get_doctor_department()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("get_doctor_department");
        }
    
        public virtual int last_generated_Appoinmentid(ObjectParameter appid)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("last_generated_Appoinmentid", appid);
        }
    
        public virtual int last_generated_Billid(ObjectParameter billid)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("last_generated_Billid", billid);
        }
    
        public virtual int last_generated_Doctorid(ObjectParameter did)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("last_generated_Doctorid", did);
        }
    
        public virtual int last_generated_id(ObjectParameter pid)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("last_generated_id", pid);
        }
    
        public virtual int last_generated_INBillid(ObjectParameter billINid)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("last_generated_INBillid", billINid);
        }
    
        public virtual int last_generated_Labid(ObjectParameter labid)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("last_generated_Labid", labid);
        }
    
        public virtual int last_generated_OpatientId(ObjectParameter oPid)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("last_generated_OpatientId", oPid);
        }
    
        public virtual int last_generated_OUTBillid(ObjectParameter billOUTid)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("last_generated_OUTBillid", billOUTid);
        }
    
        public virtual int last_generated_RoomNo(ObjectParameter roomNo)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("last_generated_RoomNo", roomNo);
        }
    
        public virtual int last_generated_Billid1(ObjectParameter billid)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("last_generated_Billid1", billid);
        }
    }
}
