//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public string LabID { get; set; }
        public string PID { get; set; }
        public string TestType { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public string Remark { get; set; }
        public string DoctorName { get; set; }
    
        public virtual PATIENT PATIENT { get; set; }
    }
}
